export const VERIFY_TOKEN_START = "VERIFY_TOKEN_START";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAIL = "VERIFY_TOKEN_FAIL";
export const VERIFY_TOKEN_CLEANUP = "VERIFY_TOKEN_CLEANUP";

export const GET_PARTIES_START = "GET_PARTIES_START";
export const GET_PARTIES_SUCCESS = "GET_PARTIES_SUCCESS";
export const GET_PARTIES_FAIL = "GET_PARTIES_FAIL";
export const GET_PARTIES_CLEANUP = "GET_PARTIES_CLEANUP";

export const GET_CALENDAR_START = "GET_CALENDAR_START";
export const GET_CALENDAR_SUCCESS = "GET_CALENDAR_SUCCESS";
export const GET_CALENDAR_FAIL = "GET_CALENDAR_FAIL";
export const GET_CALENDAR_CLEANUP = "GET_CALENDAR_CLEANUP";

export const GET_PARTY_DETAILS_START = "GET_PARTY_DETAILS_START";
export const GET_PARTY_DETAILS_SUCCESS = "GET_PARTY_DETAILS_SUCCESS";
export const GET_PARTY_DETAILS_FAIL = "GET_PARTY_DETAILS_FAIL";
export const GET_PARTY_DETAILS_CLEANUP = "GET_PARTY_DETAILS_CLEANUP";

export const CREATE_CALENDAR_START = "CREATE_CALENDAR_START";
export const CREATE_CALENDAR_SUCCESS = "CREATE_CALENDAR_SUCCESS";
export const CREATE_CALENDAR_FAIL = "CREATE_CALENDAR_FAIL";
export const CREATE_CALENDAR_CLEANUP = "CREATE_CALENDAR_CLEANUP";

export const CREATE_PARTY_START = "CREATE_PARTY_START";
export const CREATE_PARTY_SUCCESS = "CREATE_PARTY_SUCCESS";
export const CREATE_PARTY_FAIL = "CREATE_PARTY_FAIL";
export const CREATE_PARTY_CLEANUP = "CREATE_PARTY_CLEANUP";

export const CREATE_GIFT_START = "CREATE_GIFT_START";
export const CREATE_GIFT_SUCCESS = "CREATE_GIFT_SUCCESS";
export const CREATE_GIFT_FAIL = "CREATE_GIFT_FAIL";
export const CREATE_GIFT_CLEANUP = "CREATE_GIFT_CLEANUP";

export const GET_INVITE_START = "GET_INVITE_START";
export const GET_INVITE_SUCCESS = "GET_INVITE_SUCCESS";
export const GET_INVITE_FAIL = "GET_INVITE_FAIL";
export const GET_INVITE_CLEANUP = "GET_INVITE_CLEANUP";

export const GET_TRACK_STATE = "GET_TRACK_STATE";

export const CHECK_COIN = "GET_CHECK_COIN";
export const CHECK_BALANCE = "GET_CHECK_BALANCE";
export const TOPUP = "GET_TOPUP";